### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by brianwawok** [romanvm/django-tinymce4-lite#9]
Must be something obvious. Trying to use Tinymce on non-admin page forms.

Did the setup type steps. I don't see any JS or such being installed. So fine, downloaded my own tinymce.js. Include it in path. Init doesn't seem to be called.

At the point of downloading my only tinymce.js and calling init myself, what is the plugin doing for me?

I also noticed that ` {{ form.media }}` has no output, so perhaps that  is part of the problem?

On Django 1.11...

What am I missing?

**Comment by romanvm** [comment]
To tell what is wrong I need to see your code. Also I have no idea why you don't see any JS files because `django-tinymce4-lite` package contains a number of JS files that comprise TinyMCE editor. Naturally, you need to set up serving static files in your project.
Regarding `{{ form.media }}`, you need to have `form` variable in your template context that holds a Django Form object. It is automatically added by CRUD-oriented Django CBVs but if you define your view manually, you need to use a respective context variable name.
See `test_tinymce` project for an example of using TinyMCE widget on a non-admin page.

**Comment by brianwawok** [comment]
@romanvm So it should just pick up static files during collect static? I am using Pipeline with a bit of a fancy setup, so I am guessing it is somehow missing the static files from this. It fails to find the static files in both this, or the django-tinymce4 that you forked from (so not a this repo problem). But most other apps I install work fine. Maybe there is some hidden default that is making things fail with pipeline, hummm

Gotcha on the form thing. So my pages with 20 forms I would need to include it 20 times, would that work?

**Comment by romanvm** [comment]
I'm not familiar with Django-Pipeline so I cannot tell anything about it. But generally you need to run `collectstatic` to collect static files from all apps, both yours and third-party.
As for forms, if your forms use the same set of js/css files, you need to add links to those files only once. Just use a correct form name from your template context, e.g. `{{ foo_form_1.media }}`.

**Comment by romanvm** [comment]
Since there is no follow-up, I'm closing this issue.
